#ifndef SPRDEFS_H
#define SPRDEFS_H

// Some sprite definitions

// Shoot types

#define SHOT_CANNON_LEFT 47
#define SHOT_CANNON_RIGHT 48
#define SHOT_EYE_DOWN	49
#define SHOT_BASIC	50
#define SHOT_ENEMY	51
#define SHOT_LASER	52
#define SHOT_HOMING	53
#define SHOT_BOMB	54
#define SHOT_MEGA	55

#define EXPLOSION_SPR   18
#define MAINSHIP_EXPLOSION 10
#define ASTEROID_EXPL	31

// Enemies


#define ENEMY_EYE		22
#define ENEMY_CANNON_DOWN_LEFT	23
#define ENEMY_CANNON_DOWN_RIGHT 24
#define ENEMY_CANNON_UP		25
#define ENEMY_1			29
#define ENEMY_KAMIKAZE		33
#define ENEMY_FURBY		37
#define ENEMY_FINAL4_EYE        26
#define ENEMY_POWERUP		56
#define ENEMY_SHIP1		22
#define ENEMY_SHIP2		23
#define ENEMY_SHIP3		24
#define ENEMY_SHIP4		25
#define ENEMY_TURRET		26
#define ENEMY_FINAL1_SHOOT	38
#define ENEMY_ASTEROID		22
#define ENEMY_TRASH1		26
#define ENEMY_TRASH2		27
#define ENEMY_TRASH3		28
#define ENEMY_TRASH4		29
#define ENEMY_TRASH5		30
#define ENEMY_SALTARIN		22
#define ENEMY_CASCO		26
#define ENEMY_EGG		30
#define ENEMY_UGLYGUY		40
#define SHOT_CASCO_MISSILE	43
#define ENEMY_1_BIS		46

#define ENEMY_SHIP2_BIS		22
#define ENEMY_SHIP3_BIS		23
#define ENEMY_SALTARIN_BIS	24
#define ENEMY_CASCO_BIS		28
#define ENEMY_EGG_BIS		32
#define ENEMY_UGLYGUY_BIS	42
#define SHOT_CASCO_MISSILE_BIS	45
#define SHOT_MEGAMISSILE_1	38
#define SHOT_MEGAMISSILE_2	39



#define ENEMY_SHIP1_LEVEL7	22
#define ENEMY_SHIP2_LEVEL7	23
#define ENEMY_SHIP3_LEVEL7	24
#define ENEMY_SHIP4_LEVEL7	25
#define ENEMY_TURRET_LEVEL7	26
#define ENEMY_PACOSHIP_1	29
#define ENEMY_PACOSHIP_2	30
#define ENEMY_FINAL1_LEVEL7_UL	31
#define ENEMY_FINAL1_LEVEL7_UR	32
#define ENEMY_FINAL1_LEVEL7_DL	33
#define ENEMY_FINAL1_LEVEL7_DR	34



// Final enemies	
#define FINALE_SPR1		22
#define FINALE_SPR2		23
#define FINALE_SPR3		24
#define FINALE_SPR4		25
#define FINALE_SPR5		26
#define FINALE_SPR6		27
#define FINALE_SPR7		28

#endif
